# Generated by Django 5.2.8 on 2025-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='turma_responsavel',
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='gestao_escolar.disciplina'),
        ),
    ]
