# Generated by Django 5.2.8 on 2025-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
