# Generated by Django 5.2.8 on 2025-11-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0002_alter_disciplina_options_alter_nota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='media_geral',
        ),
    ]
